template update
mineiros-io/terraform-google-project pull request #15
Opened 2022-10-17 09:36 UTC by waxb

- chore: changelog updated
- chore!: update module from template and tests
- feat: computed members added

2022-10-18 08:14 UTC, zied-elouaer submitted a review, later dismissed
LGTM

2022-10-18 14:11 UTC, mariux requested changes

2022-10-18 14:11 UTC, mariux commented on iam.tf
>    authoritative = try(each.value.authoritative, true)
this looks odd as we have not converted to using index here.. please fix the map to point to the original index and use index everywhere..

2022-10-18 14:11 UTC, mariux commented on variables.tf
> +
validation is wrong. please check with iam module validation.

2022-10-19 14:04 UTC, mariux approved these changes
lgtm

2022-10-19 14:30 UTC, merged