Adding terraform google project docs
mineiros-io/terraform-google-project pull request #2
Opened 2021-10-03 21:41 UTC by Hanymin

2021-10-31 10:51 UTC, samen93 submitted a review, later dismissed

2021-10-31 10:56 UTC, samen93 approved these changes

2021-10-31 11:08 UTC, samen93 approved these changes

2021-11-01 14:57 UTC, mariux requested changes

2021-11-01 14:57 UTC, mariux commented on README.md
> +- [terraform-google-project](#terraform-google-project)
needs to be removed

2021-11-02 07:55 UTC, samen93 commented
replaced with #6

2021-11-02 07:55 UTC, closed without merging